// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4csFsAsJdMaA4wXZMNzxWhWNeyDscZwY',
    appId: '1:278795036145:web:4d959ec384e1ec626f1050',
    messagingSenderId: '278795036145',
    projectId: 'admin-dashboard-8bb5b',
    authDomain: 'admin-dashboard-8bb5b.firebaseapp.com',
    storageBucket: 'admin-dashboard-8bb5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUlr0ogjG22rzkOnxABfNsV3Kjxp1W_ew',
    appId: '1:278795036145:android:77c4b4b98e0d9fdf6f1050',
    messagingSenderId: '278795036145',
    projectId: 'admin-dashboard-8bb5b',
    storageBucket: 'admin-dashboard-8bb5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjff03r4Bqs_5Oc6j19XfN05Z9014HX5E',
    appId: '1:278795036145:ios:caf37dadae0940d86f1050',
    messagingSenderId: '278795036145',
    projectId: 'admin-dashboard-8bb5b',
    storageBucket: 'admin-dashboard-8bb5b.firebasestorage.app',
    iosBundleId: 'com.example.vrvSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjff03r4Bqs_5Oc6j19XfN05Z9014HX5E',
    appId: '1:278795036145:ios:caf37dadae0940d86f1050',
    messagingSenderId: '278795036145',
    projectId: 'admin-dashboard-8bb5b',
    storageBucket: 'admin-dashboard-8bb5b.firebasestorage.app',
    iosBundleId: 'com.example.vrvSecurity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4csFsAsJdMaA4wXZMNzxWhWNeyDscZwY',
    appId: '1:278795036145:web:29abd74fba85d30b6f1050',
    messagingSenderId: '278795036145',
    projectId: 'admin-dashboard-8bb5b',
    authDomain: 'admin-dashboard-8bb5b.firebaseapp.com',
    storageBucket: 'admin-dashboard-8bb5b.firebasestorage.app',
  );
}
